#!/bin/bash
sudo docker pull emelloul98/final-python:latest

sudo docker stop final-python || true
sudo docker rm final-python || true

sudo docker run -d -p 5000:5000 --name final-python emelloul98/final-python:latest

